[package]
name = "partyfy-rs"
version = "0.0.1"
authors = ["Dillon Mulroy <dillon.mulroy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.16.2"
gif = "0.10.3"